name = "OptimalTrainControl_v2"
uuid = "9439a33f-2b93-4fba-a0f8-3bebc99d821e"
authors = ["Vít Fanta <fantavit@fel.cvut.cz> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
